/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCapesRouteImport } from './routes/api.capes'
import { Route as ApiCapeRouteImport } from './routes/api.cape'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCapesRoute = ApiCapesRouteImport.update({
  id: '/api/capes',
  path: '/api/capes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCapeRoute = ApiCapeRouteImport.update({
  id: '/api/cape',
  path: '/api/cape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/cape': typeof ApiCapeRoute
  '/api/capes': typeof ApiCapesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/cape': typeof ApiCapeRoute
  '/api/capes': typeof ApiCapesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/cape': typeof ApiCapeRoute
  '/api/capes': typeof ApiCapesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reset-password' | '/api/cape' | '/api/capes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reset-password' | '/api/cape' | '/api/capes'
  id: '__root__' | '/' | '/reset-password' | '/api/cape' | '/api/capes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiCapeRoute: typeof ApiCapeRoute
  ApiCapesRoute: typeof ApiCapesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/capes': {
      id: '/api/capes'
      path: '/api/capes'
      fullPath: '/api/capes'
      preLoaderRoute: typeof ApiCapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cape': {
      id: '/api/cape'
      path: '/api/cape'
      fullPath: '/api/cape'
      preLoaderRoute: typeof ApiCapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiCapeRoute: ApiCapeRoute,
  ApiCapesRoute: ApiCapesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
